@host = https://localhost:7019

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName":"Cesar",
    "lastName":"Espitia",
    "email":"livecesar@gmail.com",
    "password":"ThePassword"
}