@host = https://localhost:7019

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZWIxNDY0Mi0zYzg2LTQyOTUtYjQ1YS1mMzk1ZTdiNDgyOWEiLCJnaXZlbl9uYW1lIjoiQ2VzYXIiLCJmYW1pbHlfbmFtZSI6IkVzcGl0aWEiLCJqdGkiOiJhMTJkYTI5Mi0wOTkzLTQ1NGItOWZiMC1kMWMzYmIxYWM3N2IiLCJleHAiOjE2NzE0ODQwMDAsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.jFbeCS1I_1Ro3GHDJhqRyZpsSBZ7epVjW0f1-yr6ri4